### PR TITLE
Release to production

### PR DESCRIPTION
**Pull request by manuelwedler**
This includes:
- improved chart
- IPNS removed from footer

### CODE REVIEW

**Comment by manuelwedler** [comment]
Wait there is an issue with the latest commit

**Comment by manuelwedler** [comment]
I added branch protection rules so this does not happen again

**Comment by manuelwedler** [comment]
Fixed now

**Review by kuzdogan — APPROVED** [review]

**Comment by kuzdogan** [comment]
Also turned off the coderabbit status messages like the one above

**Pull request merged**
